### ISSUE TITLE
Fetch Directed Instruction Prefetching for gem5

### ISSUE THREAD

**Issue by dhschall** [gem5/gem5#544]
[This](https://github.com/dhschall/gem5-fdp/tree/fdp) is the development repository for **Fetch Directed Instruction Prefetching (FDP)** in gem5 also known as **decoupled front-end**. FDP was originally published in [MICRO'99](https://web.eecs.umich.edu/~taustin/papers/MICRO32-fdp.pdf).
Today, FDP is the standard front-end design for high performance server CPU's including CPU's from [Intel](https://www.anandtech.com/show/16881/a-deep-dive-into-intels-alder-lake-microarchitectures/3), [IBM](https://doi.org/10.1109/ISCA45697.2020.00014), [AMD](https://www.amd.com/en/support/tech-docs/software-optimization-guide-for-the-amd-zen4-microarchitecture), and [ARM](https://doi.org/10.1109/MM.2020.2972222).

The implementation is based on an industrial [report](https://ieeexplore.ieee.org/document/9408197) and aims to establish a state-of-the-art front-end design comparable to modern servers in gem5.

## gem5 integration status
The following list tries to track integrating the changes from the development repo into the main gem5:

Pre-requirement patches to the BPU/gem5 to support decoupling:
- [x] arch: Add instruction size and PC set methods (#357)
- [x] sim: Probe listener template with lambda (#356)
- [x] cpu: Restructure BTB (#412)
- [x] cpu: Restructure RAS (#428)
- [x] cpu: Refactor indirect predictor (#429)
- [x] cpu: Branch Predictor Refactoring (#455)
- [x] cpu: Require BTB hit (#493)
- [ ] cpu: BPU support for decoupled front-end including taken-only history (#499)

Actual decoupling (Adds new stage to O3 core)
- [ ] cpu: Implement fetch target queue
- [ ] cpu: Implement decoupled front-end

Add fetch-directed prefetcher.
- [ ] cpu: Implement fetch-directed prefetcher
    > This needs to be improved.

In case there are problems, or for suggestions on improvements, please let [me](@dhschall ) know.

Finally, this could not have done without the help from others!
HUGE thanks to @rjc-arch and @andysan for performing extensive testing on all changes and code reviewing!! 
And @viditchopra1500 for extensive debugging the code for Arm implementations.

**Comment by vsoriap** [comment]
What is the status of this issue/feature? I'm experiencing low IPC in front-end bound benchmarks, and I can only apply small patches to my simulated code (Like extreme loop unrolling) to avoid branches.

**Comment by yichungchen84** [comment]
Hi all, 
I'm very interested in the this work. Please keep me posted on this progress. I can help with some testing works.
